export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const GET_USER = 'GET_USER';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const LOG_USER_IN = 'LOG_USER_IN';
export const GET_USER_OPINIONS = 'GET_USER_OPINIONS';
export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';
export const GET_USER_FOLLOWING = 'GET_USER_FOLLOWING';
export const GET_USER_LIKES = 'GET_USER_LIKES';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const TOGGLE_COMMENT_LIKE = 'LIKE_COMMENT';

export const CREATE_OPINION = 'CREATE_OPINION';
export const TOGGLE_OPINION_LIKE = 'TOGGLE_OPINION_LIKE';
export const SHOW_OPINION_COMMENTS = 'SHOW_COMMENTS';
export const EDIT_OPINION = 'EDIT_OPINION';





